@echo off
REM =====================================================================
REM  JarvisOS — CLEANUP.bat — System Cleanup Script
REM  Source: PrivacyCore ui.yml §6, JARVISOS_MASTER_PLAN §5
REM  Generated by Jarvis (RTX⚡) Build Agent 6 | 2026-05-26
REM  Clears: Windows temp, user temp, WU cache, prefetch, font cache
REM  Runs: Silent disk cleanup
REM =====================================================================

echo ========================================
echo  JarvisOS — System Cleanup
echo ========================================
echo.

REM --- Step 1: Clear Windows temp files ---
echo [1/7] Clearing Windows temp files...
if exist "%WINDIR%\Temp" (
    del /f /s /q "%WINDIR%\Temp\*.*" >nul 2>&1
    for /d %%d in ("%WINDIR%\Temp\*") do rd /s /q "%%d" 2>nul
    echo    Cleared: %%WINDIR%%\Temp
) else (
    echo    Skipped: Folder not found.
)
echo.

REM --- Step 2: Clear user temp files ---
echo [2/7] Clearing user temp files...
if exist "%TEMP%" (
    del /f /s /q "%TEMP%\*.*" >nul 2>&1
    for /d %%d in ("%TEMP%\*") do rd /s /q "%%d" 2>nul
    echo    Cleared: %%TEMP%%
) else (
    echo    Skipped: Folder not found.
)

REM Clear all users' temp folders
for /d %%u in ("C:\Users\*") do (
    if exist "%%u\AppData\Local\Temp" (
        del /f /s /q "%%u\AppData\Local\Temp\*.*" >nul 2>&1
        for /d %%d in ("%%u\AppData\Local\Temp\*") do rd /s /q "%%d" 2>nul
    )
)
echo    Cleared: All users temp folders.
echo.

REM --- Step 3: Clear Windows Update cache ---
echo [3/7] Clearing Windows Update cache...

REM Stop WU services (if running)
net stop wuauserv >nul 2>&1
net stop bits >nul 2>&1
net stop dosvc >nul 2>&1

if exist "%WINDIR%\SoftwareDistribution\Download" (
    del /f /s /q "%WINDIR%\SoftwareDistribution\Download\*.*" >nul 2>&1
    for /d %%d in ("%WINDIR%\SoftwareDistribution\Download\*") do rd /s /q "%%d" 2>nul
    echo    Cleared: SoftwareDistribution\Download
)
if exist "%WINDIR%\SoftwareDistribution\DataStore" (
    del /f /s /q "%WINDIR%\SoftwareDistribution\DataStore\*.*" >nul 2>&1
    for /d %%d in ("%WINDIR%\SoftwareDistribution\DataStore\*") do rd /s /q "%%d" 2>nul
    echo    Cleared: SoftwareDistribution\DataStore
)
echo.

REM --- Step 4: Clear Prefetch ---
echo [4/7] Clearing Prefetch cache...
if exist "%WINDIR%\Prefetch" (
    del /f /s /q "%WINDIR%\Prefetch\*.pf" >nul 2>&1
    del /f /s /q "%WINDIR%\Prefetch\*.db" >nul 2>&1
    echo    Cleared: Prefetch
) else (
    echo    Skipped: Folder not found.
)
echo.

REM --- Step 5: Clear Font Cache ---
echo [5/7] Clearing Font cache...

REM Stop font cache service
net stop FontCache >nul 2>&1
net stop FontCache3.0.0.0 >nul 2>&1

if exist "%WINDIR%\ServiceProfiles\LocalService\AppData\Local\FontCache" (
    del /f /s /q "%WINDIR%\ServiceProfiles\LocalService\AppData\Local\FontCache\*.*" >nul 2>&1
    echo    Cleared: Font cache (LocalService)
)
if exist "%LOCALAPPDATA%\Microsoft\FontCache" (
    del /f /s /q "%LOCALAPPDATA%\Microsoft\FontCache\*.*" >nul 2>&1
    echo    Cleared: Font cache (user)
)

REM Restart font cache
net start FontCache >nul 2>&1
echo.

REM --- Step 6: Clear additional caches ---
echo [6/7] Clearing additional caches...

REM Delivery Optimization cache
if exist "%WINDIR%\SoftwareDistribution\DeliveryOptimization" (
    del /f /s /q "%WINDIR%\SoftwareDistribution\DeliveryOptimization\*.*" >nul 2>&1
    echo    Cleared: Delivery Optimization cache
)

REM Thumbnail cache
del /f /s /q /a:h "%LOCALAPPDATA%\Microsoft\Windows\Explorer\thumbcache_*.db" >nul 2>&1
echo    Cleared: Thumbnail cache

REM Internet Explorer cache (leftover)
if exist "%LOCALAPPDATA%\Microsoft\Windows\INetCache" (
    del /f /s /q "%LOCALAPPDATA%\Microsoft\Windows\INetCache\*.*" >nul 2>&1
    echo    Cleared: INetCache
)

REM Recent documents
del /f /s /q "%APPDATA%\Microsoft\Windows\Recent\*.*" >nul 2>&1
echo    Cleared: Recent documents

REM Clear Start Menu pinned items (PrivacyCore technique)
if exist "%LOCALAPPDATA%\Packages\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\LocalState\start.bin" (
    del /f /q "%LOCALAPPDATA%\Packages\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\LocalState\start.bin" >nul 2>&1
    echo    Cleared: Start Menu pins (start.bin)
)
if exist "%LOCALAPPDATA%\Packages\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\LocalState\start2.bin" (
    del /f /q "%LOCALAPPDATA%\Packages\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\LocalState\start2.bin" >nul 2>&1
    echo    Cleared: Start Menu pins (start2.bin)
)

REM Delete Internet Explorer shortcuts from all users
for /d %%u in ("C:\Users\*") do (
    del /f /q "%%u\Desktop\Internet Explorer.lnk" 2>nul
    del /f /q "%%u\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Internet Explorer.lnk" 2>nul
)
del /f /q "%ProgramData%\Microsoft\Windows\Start Menu\Programs\Internet Explorer.lnk" 2>nul
echo    Cleared: IE shortcuts
echo.

REM --- Step 7: Run silent Disk Cleanup ---
echo [7/7] Running Disk Cleanup (silent mode)...

REM Pre-configure Disk Cleanup to select all categories
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches\Active Setup Temp Folders" /v "StateFlags0100" /t REG_DWORD /d 2 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches\Downloaded Program Files" /v "StateFlags0100" /t REG_DWORD /d 2 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches\Internet Cache Files" /v "StateFlags0100" /t REG_DWORD /d 2 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches\Old ChkDsk Files" /v "StateFlags0100" /t REG_DWORD /d 2 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches\Previous Installations" /v "StateFlags0100" /t REG_DWORD /d 2 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches\Recycle Bin" /v "StateFlags0100" /t REG_DWORD /d 2 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches\Setup Log Files" /v "StateFlags0100" /t REG_DWORD /d 2 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches\System error memory dump files" /v "StateFlags0100" /t REG_DWORD /d 2 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches\System error minidump files" /v "StateFlags0100" /t REG_DWORD /d 2 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches\Temporary Files" /v "StateFlags0100" /t REG_DWORD /d 2 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches\Temporary Setup Files" /v "StateFlags0100" /t REG_DWORD /d 2 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches\Thumbnail Cache" /v "StateFlags0100" /t REG_DWORD /d 2 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches\Update Cleanup" /v "StateFlags0100" /t REG_DWORD /d 2 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches\Windows Error Reporting Files" /v "StateFlags0100" /t REG_DWORD /d 2 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches\Windows Defender" /v "StateFlags0100" /t REG_DWORD /d 2 /f >nul 2>&1

REM Run cleanmgr silently with our preset (StateFlags0100)
cleanmgr /sagerun:100 >nul 2>&1
echo    Disk Cleanup executed (sagerun:100).
echo.

echo ========================================
echo  JarvisOS — System cleanup complete!
echo ========================================
exit /b 0
