@echo off
REM =====================================================================
REM  JarvisOS — EDGE.bat — Complete Microsoft Edge Removal
REM  Source: PrivacyCore components.yml §4, JARVISOS_MASTER_PLAN §5
REM  Generated by Jarvis (RTX⚡) Build Agent 6 | 2026-05-26
REM  Kills processes, removes folders, AppX, tasks, registry, shortcuts
REM =====================================================================

echo ========================================
echo  JarvisOS — Microsoft Edge Removal
echo ========================================
echo.

REM --- Step 1: Kill all Edge processes ---
echo [1/7] Killing Edge processes...
taskkill /F /IM msedge.exe >nul 2>&1
taskkill /F /IM MicrosoftEdge.exe >nul 2>&1
taskkill /F /IM MicrosoftEdgeUpdate.exe >nul 2>&1
taskkill /F /IM MicrosoftEdgeSH.exe >nul 2>&1
taskkill /F /IM MicrosoftEdgeCP.exe >nul 2>&1
taskkill /F /IM setup.exe /FI "MODULES eq msedge*" >nul 2>&1

timeout /t 2 /nobreak >nul
echo    Done.
echo.

REM --- Step 2: Remove Edge folders ---
echo [2/7] Removing Edge installation folders...

REM Program Files (x86) — primary install location
if exist "%ProgramFiles(x86)%\Microsoft\Edge" (
    rd /s /q "%ProgramFiles(x86)%\Microsoft\Edge" 2>nul
    echo    Removed: Edge (x86)
)
if exist "%ProgramFiles(x86)%\Microsoft\EdgeUpdate" (
    rd /s /q "%ProgramFiles(x86)%\Microsoft\EdgeUpdate" 2>nul
    echo    Removed: EdgeUpdate (x86)
)
if exist "%ProgramFiles(x86)%\Microsoft\EdgeCore" (
    rd /s /q "%ProgramFiles(x86)%\Microsoft\EdgeCore" 2>nul
    echo    Removed: EdgeCore (x86)
)

REM Program Files (x64) — some builds install here
if exist "%ProgramFiles%\Microsoft\Edge" (
    rd /s /q "%ProgramFiles%\Microsoft\Edge" 2>nul
    echo    Removed: Edge (x64)
)
if exist "%ProgramFiles%\Microsoft\EdgeUpdate" (
    rd /s /q "%ProgramFiles%\Microsoft\EdgeUpdate" 2>nul
    echo    Removed: EdgeUpdate (x64)
)

REM User-level Edge data
if exist "%LOCALAPPDATA%\Microsoft\Edge" (
    rd /s /q "%LOCALAPPDATA%\Microsoft\Edge" 2>nul
    echo    Removed: Edge user data
)
if exist "%LOCALAPPDATA%\Microsoft\EdgeUpdate" (
    rd /s /q "%LOCALAPPDATA%\Microsoft\EdgeUpdate" 2>nul
    echo    Removed: EdgeUpdate user data
)
echo    Done.
echo.

REM --- Step 3: Remove Edge AppX packages via PowerShell ---
echo [3/7] Removing Edge AppX packages...
powershell -NoProfile -Command "Get-AppxPackage -AllUsers *MicrosoftEdge* | Remove-AppxPackage -AllUsers -ErrorAction SilentlyContinue" 2>nul
powershell -NoProfile -Command "Get-AppxProvisionedPackage -Online | Where-Object {$_.PackageName -like '*MicrosoftEdge*'} | Remove-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue" 2>nul
echo    Done.
echo.

REM --- Step 4: Remove Edge scheduled tasks ---
echo [4/7] Removing Edge scheduled tasks...
schtasks /Delete /TN "\MicrosoftEdgeUpdateTaskMachineCore" /F >nul 2>&1
schtasks /Delete /TN "\MicrosoftEdgeUpdateTaskMachineUA" /F >nul 2>&1
schtasks /Delete /TN "\MicrosoftEdgeUpdateBrowserReplacementTask" /F >nul 2>&1

REM Delete task XML files
if exist "C:\Windows\System32\Tasks\MicrosoftEdgeUpdateTaskMachineCore" (
    del /f /q "C:\Windows\System32\Tasks\MicrosoftEdgeUpdateTaskMachineCore" 2>nul
)
if exist "C:\Windows\System32\Tasks\MicrosoftEdgeUpdateTaskMachineUA" (
    del /f /q "C:\Windows\System32\Tasks\MicrosoftEdgeUpdateTaskMachineUA" 2>nul
)
if exist "C:\Windows\System32\Tasks\MicrosoftEdgeUpdateBrowserReplacementTask" (
    del /f /q "C:\Windows\System32\Tasks\MicrosoftEdgeUpdateBrowserReplacementTask" 2>nul
)
echo    Done.
echo.

REM --- Step 5: Remove Edge registry entries ---
echo [5/7] Removing Edge registry entries...

REM Edge services
reg delete "HKLM\SYSTEM\CurrentControlSet\Services\edgeupdate" /f >nul 2>&1
reg delete "HKLM\SYSTEM\CurrentControlSet\Services\edgeupdatem" /f >nul 2>&1
reg delete "HKLM\SYSTEM\CurrentControlSet\Services\MicrosoftEdgeElevationService" /f >nul 2>&1

REM Edge App Paths
reg delete "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\msedge.exe" /f >nul 2>&1

REM Edge protocol handlers
reg delete "HKLM\SOFTWARE\Classes\MSEdgeHTM" /f >nul 2>&1
reg delete "HKLM\SOFTWARE\Classes\MSEdgePDF" /f >nul 2>&1
reg delete "HKLM\SOFTWARE\Classes\MSEdgeMHT" /f >nul 2>&1

REM Edge uninstall entries
for /f "tokens=*" %%k in ('reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall" /s /f "Microsoft Edge" /d 2^>nul ^| findstr /i "HKEY"') do (
    reg delete "%%k" /f >nul 2>&1
)
for /f "tokens=*" %%k in ('reg query "HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall" /s /f "Microsoft Edge" /d 2^>nul ^| findstr /i "HKEY"') do (
    reg delete "%%k" /f >nul 2>&1
)

REM Block EdgeUpdate reinstallation
reg add "HKLM\SOFTWARE\Policies\Microsoft\EdgeUpdate" /v "UpdateDefault" /t REG_DWORD /d 0 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Policies\Microsoft\EdgeUpdate" /v "InstallDefault" /t REG_DWORD /d 0 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Policies\Microsoft\EdgeUpdate" /v "DoNotUpdateToEdgeWithChromium" /t REG_DWORD /d 1 /f >nul 2>&1

REM Remove Edge from OpenWithProgIds
reg delete "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.htm\OpenWithProgids" /v "MSEdgeHTM" /f >nul 2>&1
reg delete "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.html\OpenWithProgids" /v "MSEdgeHTM" /f >nul 2>&1
reg delete "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.pdf\OpenWithProgids" /v "MSEdgePDF" /f >nul 2>&1
echo    Done.
echo.

REM --- Step 6: Clean up Start Menu and Desktop shortcuts ---
echo [6/7] Removing Edge shortcuts...

REM Desktop shortcuts
del /f /q "%PUBLIC%\Desktop\Microsoft Edge.lnk" 2>nul
del /f /q "%USERPROFILE%\Desktop\Microsoft Edge.lnk" 2>nul

REM Start Menu
del /f /q "%ProgramData%\Microsoft\Windows\Start Menu\Programs\Microsoft Edge.lnk" 2>nul
del /f /q "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Microsoft Edge.lnk" 2>nul

REM Quick Launch
del /f /q "%APPDATA%\Microsoft\Internet Explorer\Quick Launch\Microsoft Edge.lnk" 2>nul

REM TaskBar pin
del /f /q "%APPDATA%\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Microsoft Edge.lnk" 2>nul

REM All users Start Menu
for /d %%u in ("C:\Users\*") do (
    del /f /q "%%u\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Microsoft Edge.lnk" 2>nul
    del /f /q "%%u\Desktop\Microsoft Edge.lnk" 2>nul
    del /f /q "%%u\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\Microsoft Edge.lnk" 2>nul
    del /f /q "%%u\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Microsoft Edge.lnk" 2>nul
)
echo    Done.
echo.

REM --- Step 7: Final verification ---
echo [7/7] Verifying removal...
if not exist "%ProgramFiles(x86)%\Microsoft\Edge" (
    echo    [OK] Edge installation folder removed.
) else (
    echo    [WARN] Edge folder still present — may need TrustedInstaller privileges.
)
echo.
echo ========================================
echo  JarvisOS — Edge removal complete!
echo ========================================
exit /b 0
