@echo off
REM =====================================================================
REM  JarvisOS — ONEDRIVE.bat — Complete OneDrive Removal
REM  Source: PrivacyCore components.yml §4, JARVISOS_MASTER_PLAN §5
REM  Generated by Jarvis (RTX⚡) Build Agent 6 | 2026-05-26
REM  Kills processes, uninstalls, removes folders, registry, Explorer sidebar
REM =====================================================================

echo ========================================
echo  JarvisOS — OneDrive Removal
echo ========================================
echo.

REM --- Step 1: Kill OneDrive processes ---
echo [1/6] Killing OneDrive processes...
taskkill /F /IM OneDrive.exe >nul 2>&1
taskkill /F /IM OneDriveSetup.exe >nul 2>&1
taskkill /F /IM OneDriveStandaloneUpdater.exe >nul 2>&1
taskkill /F /IM FileCoAuth.exe >nul 2>&1
timeout /t 2 /nobreak >nul
echo    Done.
echo.

REM --- Step 2: Run OneDrive uninstaller ---
echo [2/6] Running OneDrive uninstaller...

REM Try System32 uninstaller first (64-bit)
if exist "%SystemRoot%\System32\OneDriveSetup.exe" (
    "%SystemRoot%\System32\OneDriveSetup.exe" /uninstall >nul 2>&1
    echo    Ran System32 uninstaller.
)

REM Try SysWOW64 uninstaller (32-bit on 64-bit OS)
if exist "%SystemRoot%\SysWOW64\OneDriveSetup.exe" (
    "%SystemRoot%\SysWOW64\OneDriveSetup.exe" /uninstall >nul 2>&1
    echo    Ran SysWOW64 uninstaller.
)

REM Try user-level uninstaller
if exist "%LOCALAPPDATA%\Microsoft\OneDrive\OneDriveSetup.exe" (
    "%LOCALAPPDATA%\Microsoft\OneDrive\OneDriveSetup.exe" /uninstall >nul 2>&1
    echo    Ran user-level uninstaller.
)
timeout /t 3 /nobreak >nul
echo    Done.
echo.

REM --- Step 3: Remove OneDrive folders ---
echo [3/6] Removing OneDrive folders...

REM User-level OneDrive data
if exist "%LOCALAPPDATA%\Microsoft\OneDrive" (
    rd /s /q "%LOCALAPPDATA%\Microsoft\OneDrive" 2>nul
    echo    Removed: OneDrive local data
)
if exist "%USERPROFILE%\OneDrive" (
    rd /s /q "%USERPROFILE%\OneDrive" 2>nul
    echo    Removed: OneDrive user folder
)

REM ProgramData
if exist "%ProgramData%\Microsoft OneDrive" (
    rd /s /q "%ProgramData%\Microsoft OneDrive" 2>nul
    echo    Removed: OneDrive ProgramData
)
if exist "%ProgramData%\Microsoft\OneDrive" (
    rd /s /q "%ProgramData%\Microsoft\OneDrive" 2>nul
    echo    Removed: OneDrive ProgramData (alt path)
)

REM System-level setup files
if exist "%SystemRoot%\System32\OneDriveSetup.exe" (
    del /f /q "%SystemRoot%\System32\OneDriveSetup.exe" 2>nul
    echo    Removed: OneDriveSetup.exe (System32)
)
if exist "%SystemRoot%\SysWOW64\OneDriveSetup.exe" (
    del /f /q "%SystemRoot%\SysWOW64\OneDriveSetup.exe" 2>nul
    echo    Removed: OneDriveSetup.exe (SysWOW64)
)

REM Temp folder
if exist "%LOCALAPPDATA%\OneDrive" (
    rd /s /q "%LOCALAPPDATA%\OneDrive" 2>nul
    echo    Removed: OneDrive temp data
)

REM All users cleanup
for /d %%u in ("C:\Users\*") do (
    if exist "%%u\AppData\Local\Microsoft\OneDrive" (
        rd /s /q "%%u\AppData\Local\Microsoft\OneDrive" 2>nul
    )
    if exist "%%u\OneDrive" (
        rd /s /q "%%u\OneDrive" 2>nul
    )
)
echo    Done.
echo.

REM --- Step 4: Remove OneDrive registry entries ---
echo [4/6] Removing OneDrive registry entries...

REM Disable OneDrive via Group Policy
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\OneDrive" /v "DisableFileSyncNGSC" /t REG_DWORD /d 1 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\OneDrive" /v "DisableFileSync" /t REG_DWORD /d 1 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\OneDrive" /v "DisableMeteredNetworkFileSync" /t REG_DWORD /d 1 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\OneDrive" /v "DisableLibrariesDefaultSaveToOneDrive" /t REG_DWORD /d 1 /f >nul 2>&1

REM Remove OneDrive from startup
reg delete "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" /v "OneDrive" /f >nul 2>&1
reg delete "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" /v "OneDriveSetup" /f >nul 2>&1

REM Remove OneDrive service
reg delete "HKLM\SYSTEM\CurrentControlSet\Services\OneSyncSvc" /f >nul 2>&1

REM Remove OneDrive uninstall entry
for /f "tokens=*" %%k in ('reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall" /s /f "OneDrive" /d 2^>nul ^| findstr /i "HKEY"') do (
    reg delete "%%k" /f >nul 2>&1
)

REM Reset User Shell Folders to default (in case OneDrive hijacked them)
reg add "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" /v "Desktop" /t REG_EXPAND_SZ /d "%%USERPROFILE%%\Desktop" /f >nul 2>&1
reg add "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" /v "Personal" /t REG_EXPAND_SZ /d "%%USERPROFILE%%\Documents" /f >nul 2>&1
reg add "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" /v "My Pictures" /t REG_EXPAND_SZ /d "%%USERPROFILE%%\Pictures" /f >nul 2>&1
reg add "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" /v "My Music" /t REG_EXPAND_SZ /d "%%USERPROFILE%%\Music" /f >nul 2>&1
reg add "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" /v "My Video" /t REG_EXPAND_SZ /d "%%USERPROFILE%%\Videos" /f >nul 2>&1
echo    Done.
echo.

REM --- Step 5: Remove OneDrive from Explorer sidebar ---
echo [5/6] Removing OneDrive from Explorer sidebar...

REM CLSID for OneDrive in Navigation Pane
reg add "HKCR\CLSID\{018D5C66-4533-4307-9B53-224DE2ED1FE6}" /v "System.IsPinnedToNameSpaceTree" /t REG_DWORD /d 0 /f >nul 2>&1
reg add "HKCR\Wow6432Node\CLSID\{018D5C66-4533-4307-9B53-224DE2ED1FE6}" /v "System.IsPinnedToNameSpaceTree" /t REG_DWORD /d 0 /f >nul 2>&1

REM Remove from namespace
reg delete "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace\{018D5C66-4533-4307-9B53-224DE2ED1FE6}" /f >nul 2>&1
reg delete "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace\{018D5C66-4533-4307-9B53-224DE2ED1FE6}" /f >nul 2>&1

REM Remove IPropertySetStorage CLSID entries
reg delete "HKCR\CLSID\{018D5C66-4533-4307-9B53-224DE2ED1FE6}\Instance" /f >nul 2>&1
echo    Done.
echo.

REM --- Step 6: Final verification ---
echo [6/6] Verifying removal...
if not exist "%LOCALAPPDATA%\Microsoft\OneDrive" (
    echo    [OK] OneDrive local data removed.
) else (
    echo    [WARN] OneDrive folder still present — may need re-run after reboot.
)
echo.
echo ========================================
echo  JarvisOS — OneDrive removal complete!
echo ========================================
exit /b 0
