@echo off
REM =====================================================================
REM  JarvisOS — SFC_STUB.bat — SFC Replacement Stub
REM  Source: Privacy+ v0.8.3 SFCDEPLOY technique, JARVISOS_MASTER_PLAN §9
REM  Generated by Jarvis (RTX⚡) Build Agent 6 | 2026-05-26
REM  Purpose: Replace sfc.exe with a stub that exits immediately
REM  This prevents Windows from using SFC to re-download/restore
REM  components we deliberately removed (Edge, OneDrive, IE, etc.)
REM =====================================================================

echo ========================================
echo  JarvisOS — SFC Stub Deployment
echo ========================================
echo.

REM --- Check admin privileges ---
echo [1/4] Checking administrator privileges...
net session >nul 2>&1
if %errorlevel% neq 0 (
    echo    [ERROR] This script requires administrator privileges.
    echo    Please run as Administrator.
    pause
    exit /b 1
)
echo    [OK] Running as Administrator.
echo.

REM --- Define paths ---
set "SFC_PATH=%SystemRoot%\System32\sfc.exe"
set "SFC_BACKUP=%SystemRoot%\System32\sfc.exe.jarvis_backup"
set "SFC_STUB_SRC=%~dp0sfc_stub.exe"

REM --- Step 2: Take ownership of sfc.exe ---
echo [2/4] Taking ownership of sfc.exe...

REM Take ownership from TrustedInstaller
takeown /f "%SFC_PATH%" /a >nul 2>&1
if %errorlevel% neq 0 (
    echo    [WARN] takeown failed — trying icacls...
)

REM Grant Administrators full control
icacls "%SFC_PATH%" /grant Administrators:F >nul 2>&1
if %errorlevel% neq 0 (
    echo    [ERROR] Could not set permissions on sfc.exe.
    echo    You may need to boot into Safe Mode or use TrustedInstaller token.
    pause
    exit /b 1
)
echo    [OK] Ownership and permissions set.
echo.

REM --- Step 3: Backup original sfc.exe ---
echo [3/4] Backing up original sfc.exe...
if not exist "%SFC_BACKUP%" (
    copy /y "%SFC_PATH%" "%SFC_BACKUP%" >nul 2>&1
    if %errorlevel% equ 0 (
        echo    [OK] Original backed up to: sfc.exe.jarvis_backup
    ) else (
        echo    [ERROR] Failed to create backup.
        pause
        exit /b 1
    )
) else (
    echo    [OK] Backup already exists — skipping.
)
echo.

REM --- Step 4: Create stub and replace sfc.exe ---
echo [4/4] Deploying SFC stub...

REM Create a minimal batch-based stub
REM The stub simply outputs a message and exits with 0
REM We create a tiny .exe-like script that does nothing

REM Method: Create a minimal CMD stub that replaces sfc.exe
REM Since we can't easily create an .exe from batch, we use the
REM "copy con" technique to create a minimal script

REM Delete existing sfc.exe
del /f /q "%SFC_PATH%" >nul 2>&1
if %errorlevel% neq 0 (
    echo    [ERROR] Could not delete sfc.exe — file may be in use.
    echo    Try running this in Safe Mode.
    pause
    exit /b 1
)

REM Create a stub batch file that acts as sfc.exe
REM We write a small script that exits immediately
(
    echo @echo off
    echo REM JarvisOS SFC Stub — prevents component restoration
    echo REM Original backed up as sfc.exe.jarvis_backup
    echo REM To restore: copy sfc.exe.jarvis_backup sfc.exe
    echo exit /b 0
) > "%SFC_PATH%" 2>nul

if exist "%SFC_PATH%" (
    echo    [OK] SFC stub deployed successfully.
    echo    Windows can no longer use SFC to restore removed components.
    echo.
    echo    NOTE: Original sfc.exe backed up as:
    echo      %SFC_BACKUP%
    echo    To restore original SFC functionality:
    echo      copy "%SFC_BACKUP%" "%SFC_PATH%"
) else (
    echo    [ERROR] Failed to create stub.
    echo    Restoring backup...
    copy /y "%SFC_BACKUP%" "%SFC_PATH%" >nul 2>&1
    pause
    exit /b 1
)

echo.
echo ========================================
echo  JarvisOS — SFC stub deployment complete!
echo ========================================
exit /b 0
